### PR TITLE
Adding footer

### PR DESCRIPTION
**Pull request by saimadhav24**
[](https://pr-43.company.com) [PR 43](https://pr-43.company.com) Medium saimadhav24 Test plan false      Completed

# Description

Added a footer to the website(https://github.com/ank1traj/testcase-generator/issues/16)

Fixes # (issue)

* Added a footer to the website
* Removed "By Ankit Raj" when screen size is becoming smaller
* Removed pointer-events for "By Ankit Raj"
## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* Firmware version: KXG60ZNV512G_KIOXIAAGHA4101
* Hardware: 8 gb ram, 4 gb graphics card, intel i5 processor
* Toolchain:
* SDK:

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (there are no changes to added to my best knowledge)
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by saimadhav24** [comment]
@ank1traj It is still showing authorization required to deploy
image

**Comment by ank1traj** [comment]
@saimadhav24 @material-ui/icons this package is creating issue. Can we use other npm package?

**Comment by saimadhav24** [comment]
@ank1traj I should be changing the location of footer ri8?

**Comment by ank1traj** [comment]
@saimadhav24 On generating larger data footer is overlapping with data.

**Comment by ank1traj** [comment]
> > @saimadhav24 On generating larger data footer is overlapping with data.
> 
> Can you share some screenshots i will look into it

image

**Comment by saimadhav24** [comment]
@ank1traj So i have found a temporary solution, i dont know whether its feasible or not, so I have added `<Footer/>` to every page and this is the result i have got,these are few examples

image

image

image

**Comment by saimadhav24** [comment]
@ank1traj should i push my code?

**Review by ank1traj — APPROVED** [review]

**Pull request merged**
