### PR TITLE
Improve UI

### PR DESCRIPTION
**Pull request by Deveesh-Shetty**
[](https://pr-28.company.com) [PR 28](https://pr-28.company.com) Medium Deveesh-Shetty false      Completed

# Description

Improved the UI for the different test generator pages. 

Also moved the styled UI components to a different file, so that in all the other components you can just import them rather than typing it all again...

Fixes this issue #15 

## Type of change

Please delete options that are not relevant.

- [x] UI change (non-breaking change which fixes an issue)

# How Has This Been Tested?

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings

### CODE REVIEW

**Review by ank1traj — COMMENTED** [review]
Congratulations on opening your first pull request to the project! A core maintainer will review your contribution shortly.

**Comment by Deveesh-Shetty** [comment]
> Congratulations on opening your first pull request to the project! A core maintainer will review your contribution shortly.

Thank you :)
WIll try to contribute more soon...

**Comment by ank1traj** [comment]
Hi @Deveesh-Shetty 

Please resolve the issue raise at https://deepscan.io/dashboard/#view=project&tid=15696&pid=24372&bid=749403&subview=pull-request&prid=1591842

Also, rebase the branch with the latest main branch. Pushed some major changes today

**Comment by Deveesh-Shetty** [comment]
> Hi @Deveesh-Shetty
> 
> Please resolve the issue raise at https://deepscan.io/dashboard/#view=project&tid=15696&pid=24372&bid=749403&subview=pull-request&prid=1591842
> 
> Also, rebase the branch with the latest main branch. Pushed some major changes today.
> 
> And, need to fix the issues in light mode. Please visit in light mode https://testcase-generator-git-fork-deveesh-shetty-improve-ui-ank1traj.vercel.app/generator/stringGenerator

Oh yeah... will fix it and update

**Comment by Deveesh-Shetty** [comment]
I had exams in middle, so lost track with it and stuck with bunch of conflicts and random stuffs....

**Comment by ank1traj** [comment]
> I had exams in middle, so lost track with it and stuck with bunch of conflicts and random stuffs....
> 
> Will close this PR and create a new one soon....
> 
> Or is there any better way

@Deveesh-Shetty Go with the second one.

**Comment by Deveesh-Shetty** [comment]
> > I had exams in middle, so lost track with it and stuck with bunch of conflicts and random stuffs....
> > 
> > Will close this PR and create a new one soon....
> > 
> > Or is there any better way
> 
> @Deveesh-Shetty Go with the second one. 

Closing PR?

**Pull request closed without merging**
