### PR TITLE
Navigation bar Issue #14

### LINKED ISSUE #14: Add navigation bar
Adding a navigation bar to the website will make it easier for users to navigate through the website and find the information they need. The navigation bar can be placed at the top of the website and can include links to different pages on the website, such as the home page, about us page, contact us page and other relevant pages.

The navigation bar should be designed in a way that is user-friendly and easy to understand. It should be visually appealing, and the links should be organized in a logical manner. It is also important to ensure that the navigation bar is responsive and works well on all devices, including desktops, laptops, tablets, and smartphones.

In addition to the navigation bar, it may also be useful to include a search bar on the website, allowing users to quickly search for specific information they need. This can be especially useful for larger websites with a lot of content.

Overall, adding a navigation bar and search bar to the website will improve user experience and make it easier for users to find the information they need.

### PR DESCRIPTION
**Pull request by yuvrxj-afk**
[](https://pr-26.company.com) [PR 26](https://pr-26.company.com) yuvrxj-afk Test plan false      Completed

# Description
Added a Navbar which include links to different pages on the website, such as the home page, about us page, contact us page and other relevant pages.

Fixes # (Add Navigation Bar) #14 

## Type of change
Removed the Contribute section and added to navbar , media queries to be defined in the next commit after a review. 

Please delete options that are not relevant.

- [&#10004;] Bug fix (non-breaking change which fixes an issue)

- [&#10004;] New feature (non-breaking change which adds functionality)
- [] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [] This change requires a documentation update

# Checklist:

- [&#10004;] My code follows the style guidelines of this project
- [&#10004;] I have performed a self-review of my own code
- [&#10004; ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [&#10004; ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by ank1traj — COMMENTED** [review]
Congratulations on opening your first pull request to the project! A core maintainer will review your contribution shortly.

**Comment by ank1traj** [comment]
Hi @yuvrxj-afk 

please remove the package-lock.json file

**Comment by ank1traj** [comment]
#### 📝 Changed routes:


| [**/**](https://testcase-generator-j87rbb94t-ank1traj.vercel.app/) |
|:-:|
|<a href="https://testcase-generator-j87rbb94t-ank1traj.vercel.app/">Screenshot of /</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/TAODm2gBeNhTT81BwosxE5S8E6qDUNi3Tx5qNWJx5j7zMU0h22nXKO2sGDwNuq1ty5gVIY26-XAZxqbR59iqVQ.png">(view full size)</a> |







Commit 6bb2c53ff9d2945d2587ffc53b7bf335c4ca19e5 (https://testcase-generator-j87rbb94t-ank1traj.vercel.app).

**Comment by ank1traj** [comment]
@yuvrxj-afk Aren't we going to add navigation bar in every routes and also I think navigation bar is not responsive. Correct me if I am wrong.

**Comment by yuvrxj-afk** [comment]
We need to remove components from index.js and I mean that create nav/description/cards separately , not in a single file, then It won't be so complex.

**Comment by ank1traj** [comment]
@yuvrxj-afk This should be done completely. If you don't have bandwidth/time you can convey that. What is required is complete closure of the issue. Not by part by part.

**Comment by yuvrxj-afk** [comment]
I'm having some work , will try to commit soon @ank1traj In between if anyone can contribute that would be so great.

**Comment by yuvrxj-afk** [comment]
will be adding rest pages in issues , where others can contribute to navbar linked pages.

**Comment by ank1traj** [comment]
@yuvrxj-afk Could you please resolve the conflicts?

**Comment by yuvrxj-afk** [comment]
@ank1traj would you please review?

**Comment by ank1traj** [comment]
> @ank1traj would you please review?

Dropped some comments. Have a look.

**Comment by yuvrxj-afk** [comment]
> > @ank1traj would you please review?
> 
> Dropped some comments. Have a look.
Sentry ones?

**Comment by yuvrxj-afk** [comment]
> > Dropped some comments. Have a look.
> > Didn't get it. Sentry ones?

**Comment by ank1traj** [comment]
> > > Dropped some comments. Have a look.
> > > Didn't get it. Sentry ones?

First deployment is getting failed due to searchbar not found
image


Second if you see the review one. You will get my comment. Even if you scroll this PR you will get that.

**Comment by ank1traj** [comment]
@yuvrxj-afk what was the need of search bar? What it's providing here?

**Comment by yuvrxj-afk** [comment]
You mentioned the search bar in the navbar issue's description, so created the component, which can be used later with functionality.

**Comment by yuvrxj-afk** [comment]
Surely, i should make one more commit , we'll add it later with functionalities as we have to fetch as well.

**Review by ank1traj — APPROVED** [review]

**Pull request merged**
